title: Alicia Talavera
#logo: assets/img/avatar.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
header_pages:
  - proyectos.md
include:
  - _data
social_links:
  - name: GitHub
    url: https://github.com/tuusuario
  - name: LinkedIn
    url: https://www.linkedin.com/in/tuusuario
