title: Alicia Talavera
logo: assets/img/avatar.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minima

navigation:
  - title: Inicio
    url: /
  - title: Proyectos
    url: /proyectos/

show_nav: true
