title: Alicia Talavera
logo: assets/img/avatar.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
include:
  - _pages
header_pages:
  - proyectos.md
include:
  - _pages
