title: Alicia Talaveera
logo: assets/img/avatar.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-hacker

navigation:
  - title: Inicio
    url: /
  - title: Proyectos
    url: /proyectos/

show_nav: true
