title: Alicia Talavera
#logo: assets/img/avatar.png
#description: text below image
#show_downloads: true
minimal_mistakes_skin: default

navigation:
  - name: main
  items: navigation.yml
include:
  - _data
